{pkgs}: {
    deps = [
      pkgs.noto-fonts-monochrome-emoji
      pkgs.jdk17
      pkgs.gradle
      pkgs.unzip
      pkgs.noto-fonts-cjk-serif
      pkgs.noto-fonts-cjk-sans
      pkgs.noto-fonts
      pkgs.chromium
      pkgs.libgbm
      pkgs.gdk-pixbuf
      pkgs.gtk3
      pkgs.freetype
      pkgs.fontconfig
      pkgs.expat
      pkgs.xorg.libxshmfence
      pkgs.xorg.libxcb
      pkgs.xorg.libXtst
      pkgs.xorg.libXrender
      pkgs.xorg.libXext
      pkgs.xorg.libX11
      pkgs.alsa-lib
      pkgs.cairo
      pkgs.pango
      pkgs.mesa
      pkgs.xorg.libXrandr
      pkgs.xorg.libXfixes
      pkgs.xorg.libXdamage
      pkgs.xorg.libXcomposite
      pkgs.at-spi2-core
      pkgs.libxkbcommon
      pkgs.dbus
      pkgs.libdrm
      pkgs.cups
      pkgs.at-spi2-atk
      pkgs.atk
      pkgs.nspr
      pkgs.nss
      pkgs.glib
    ];
  }
  