import { useState, useEffect, useRef, useCallback } from 'react';
import { Heart, MessageCircle, Flag, MoreHorizontal, Pin, EyeOff, Trash2, Send, Image, X, ChevronDown, AlertTriangle, Shield, Trophy, Bird, Award, Star, Share2 } from 'lucide-react';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { useToast } from '@/hooks/use-toast';
import { useGetMe } from '@workspace/api-client-react';
import { useActiveOrgContext } from '@/context/ActiveOrgContext';

const BASE_URL = (import.meta.env.BASE_URL ?? '/').replace(/\/$/, '');
function API(path: string) { return `${BASE_URL}/api${path}`; }

function timeAgo(dateStr: string) {
  const diff = (Date.now() - new Date(dateStr).getTime()) / 1000;
  if (diff < 60) return 'just now';
  if (diff < 3600) return `${Math.floor(diff / 60)}m ago`;
  if (diff < 86400) return `${Math.floor(diff / 3600)}h ago`;
  return new Date(dateStr).toLocaleDateString('en-IN', { day: 'numeric', month: 'short' });
}

type PostType = 'member_post' | 'achievement' | 'club_announcement';

interface FeedPost {
  id: number;
  type: PostType;
  body: string;
  privacy: 'all_members' | 'followers_only';
  isPinned: boolean;
  isHidden: boolean;
  taggedCourseId: number | null;
  taggedHoleNumber: number | null;
  achievementType: string | null;
  reactionsCount: number;
  commentsCount: number;
  createdAt: string;
  authorUserId: number | null;
  authorDisplayName: string | null;
  authorUsername: string | null;
  authorProfileImage: string | null;
  media: { url: string; mimeType: string; sortOrder: number }[];
  hasReacted: boolean;
  // Task #708 — set when this post was generated by posting a highlight reel
  // to the feed. Powers the in-feed view + re-share engagement pings.
  reelId: number | null;
}

interface Comment {
  id: number;
  body: string;
  createdAt: string;
  authorUserId: number | null;
  authorDisplayName: string | null;
  authorUsername: string | null;
  authorProfileImage: string | null;
}

interface Report {
  id: number;
  postId: number | null;
  reason: string;
  notes: string | null;
  status: string;
  createdAt: string;
  reporterDisplayName: string | null;
  reporterUsername: string | null;
  post: { id: number; body: string; isHidden: boolean } | null;
}

const ACHIEVEMENT_ICONS: Record<string, { icon: React.ComponentType<{ className?: string }>; label: string; color: string }> = {
  hole_in_one: { icon: Star, label: 'Hole in One!', color: 'text-yellow-400' },
  eagle: { icon: Bird, label: 'Eagle', color: 'text-emerald-400' },
  personal_best: { icon: Award, label: 'Personal Best', color: 'text-blue-400' },
  tournament_win: { icon: Trophy, label: 'Tournament Win', color: 'text-primary' },
};

function AvatarPlaceholder({ name, size = 'md' }: { name: string | null; size?: 'sm' | 'md' }) {
  const initials = name ? name.split(' ').map(n => n[0]).join('').slice(0, 2).toUpperCase() : '?';
  const sz = size === 'sm' ? 'w-8 h-8 text-xs' : 'w-10 h-10 text-sm';
  return (
    <div className={`${sz} rounded-full bg-primary/20 border border-primary/30 flex items-center justify-center font-bold text-primary flex-shrink-0`}>
      {initials}
    </div>
  );
}

export function PostCard({
  post,
  orgId,
  currentUserId,
  isAdmin,
  onDelete,
  onReact,
  onPin,
  onHide,
}: {
  post: FeedPost;
  orgId: number;
  currentUserId: number | undefined;
  isAdmin: boolean;
  onDelete: (id: number) => void;
  onReact: (id: number, reacted: boolean) => void;
  onPin: (id: number, pinned: boolean) => void;
  onHide: (id: number, hidden: boolean) => void;
}) {
  const { toast } = useToast();
  const [showComments, setShowComments] = useState(false);
  const [comments, setComments] = useState<Comment[]>([]);
  const [commentsLoading, setCommentsLoading] = useState(false);
  const [commentText, setCommentText] = useState('');
  const [submittingComment, setSubmittingComment] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  const [showReportModal, setShowReportModal] = useState(false);
  const [reportReason, setReportReason] = useState('inappropriate');
  const [reportNotes, setReportNotes] = useState('');
  const menuRef = useRef<HTMLDivElement>(null);
  // Task #708 — fire a single 'view' engagement ping the first time the
  // viewer watches the reel for ≥2s. Tracked in a ref (not state) so the
  // <video onTimeUpdate> handler doesn't have to re-bind on every render.
  const viewLoggedRef = useRef(false);

  function logReelEngagement(type: 'view' | 'feed_share') {
    if (!post.reelId) return;
    try {
      fetch(API(`/portal/highlights/${post.reelId}/events`), {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify({ type, source: 'web_feed' }),
      }).catch(() => { /* best-effort analytics */ });
    } catch { /* best-effort analytics */ }
  }

  function handleVideoTimeUpdate(e: React.SyntheticEvent<HTMLVideoElement>) {
    if (viewLoggedRef.current || !post.reelId) return;
    if (e.currentTarget.currentTime >= 2) {
      viewLoggedRef.current = true;
      logReelEngagement('view');
    }
  }

  async function shareReelFromFeed() {
    if (!post.reelId) return;
    const videoMedia = post.media.find(m => m.mimeType?.startsWith('video/'));
    if (!videoMedia) return;
    const shareUrl = videoMedia.url.startsWith('http')
      ? videoMedia.url
      : `${window.location.origin}${videoMedia.url}`;
    let shared = false;
    try {
      const nav = navigator as Navigator & { share?: (data: ShareData) => Promise<void> };
      if (typeof nav.share === 'function') {
        await nav.share({
          title: post.body || 'Highlight reel',
          url: shareUrl,
        });
        shared = true;
      }
    } catch {
      /* user cancelled — don't fall through to clipboard */
      return;
    }
    if (!shared) {
      try {
        await navigator.clipboard.writeText(shareUrl);
        toast({ title: 'Link copied', description: 'Reel link copied to your clipboard.' });
        shared = true;
      } catch {
        toast({ title: 'Sharing unavailable', description: 'Could not copy the link.' });
      }
    }
    if (shared) logReelEngagement('feed_share');
  }

  useEffect(() => {
    function handler(e: MouseEvent) {
      if (menuRef.current && !menuRef.current.contains(e.target as Node)) setMenuOpen(false);
    }
    if (menuOpen) document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, [menuOpen]);

  async function loadComments() {
    if (commentsLoading) return;
    setCommentsLoading(true);
    try {
      const r = await fetch(API(`/organizations/${orgId}/feed/posts/${post.id}/comments`), { credentials: 'include' });
      if (r.ok) setComments(await r.json());
    } finally {
      setCommentsLoading(false);
    }
  }

  function toggleComments() {
    if (!showComments) loadComments();
    setShowComments(v => !v);
  }

  async function submitComment() {
    if (!commentText.trim()) return;
    setSubmittingComment(true);
    try {
      const r = await fetch(API(`/organizations/${orgId}/feed/posts/${post.id}/comments`), {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify({ body: commentText }),
      });
      if (r.ok) {
        const c = await r.json();
        setComments(prev => [...prev, c]);
        setCommentText('');
      }
    } finally {
      setSubmittingComment(false);
    }
  }

  async function deleteComment(commentId: number) {
    await fetch(API(`/organizations/${orgId}/feed/posts/${post.id}/comments/${commentId}`), {
      method: 'DELETE', credentials: 'include',
    });
    setComments(prev => prev.filter(c => c.id !== commentId));
  }

  async function submitReport() {
    await fetch(API(`/organizations/${orgId}/feed/posts/${post.id}/report`), {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      credentials: 'include',
      body: JSON.stringify({ reason: reportReason, notes: reportNotes }),
    });
    toast({ title: 'Reported', description: 'Thank you, admins have been notified.' });
    setShowReportModal(false);
    setReportNotes('');
  }

  const isOwner = post.authorUserId === currentUserId;
  const achievementMeta = post.achievementType ? ACHIEVEMENT_ICONS[post.achievementType] : null;

  const postTypeBadge = post.type === 'club_announcement'
    ? <Badge className="text-[10px] bg-primary/20 text-primary border-primary/30">📌 Announcement</Badge>
    : post.type === 'achievement' && achievementMeta
    ? <Badge className={`text-[10px] bg-white/10 border-white/10 ${achievementMeta.color}`}>{achievementMeta.label}</Badge>
    : null;

  return (
    <Card className="bg-card border-white/5 p-4 space-y-3 relative">
      {post.isPinned && (
        <div className="absolute top-3 right-3">
          <Pin className="w-3.5 h-3.5 text-primary opacity-60" />
        </div>
      )}

      {/* Header */}
      <div className="flex items-start gap-3">
        {post.authorProfileImage
          ? <img src={post.authorProfileImage} alt="" className="w-10 h-10 rounded-full object-cover flex-shrink-0" />
          : <AvatarPlaceholder name={post.authorDisplayName || post.authorUsername} />
        }
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 flex-wrap">
            <span className="font-semibold text-sm text-white">
              {post.authorDisplayName || post.authorUsername || 'Club'}
            </span>
            {postTypeBadge}
          </div>
          <p className="text-xs text-muted-foreground">{timeAgo(post.createdAt)}</p>
        </div>
        {/* Menu */}
        <div className="relative" ref={menuRef}>
          <button
            onClick={() => setMenuOpen(v => !v)}
            className="text-muted-foreground hover:text-white p-1 rounded"
          >
            <MoreHorizontal className="w-4 h-4" />
          </button>
          {menuOpen && (
            <div className="absolute right-0 top-7 z-50 w-48 bg-card border border-white/10 rounded-xl shadow-xl overflow-hidden">
              {(isOwner || isAdmin) && (
                <button
                  onClick={() => { setMenuOpen(false); onDelete(post.id); }}
                  className="w-full flex items-center gap-2 px-3 py-2 text-sm text-red-400 hover:bg-white/5"
                >
                  <Trash2 className="w-3.5 h-3.5" /> Delete Post
                </button>
              )}
              {isAdmin && (
                <>
                  <button
                    onClick={() => { setMenuOpen(false); onPin(post.id, !post.isPinned); }}
                    className="w-full flex items-center gap-2 px-3 py-2 text-sm text-white/70 hover:bg-white/5"
                  >
                    <Pin className="w-3.5 h-3.5" /> {post.isPinned ? 'Unpin' : 'Pin'} Post
                  </button>
                  <button
                    onClick={() => { setMenuOpen(false); onHide(post.id, !post.isHidden); }}
                    className="w-full flex items-center gap-2 px-3 py-2 text-sm text-white/70 hover:bg-white/5"
                  >
                    <EyeOff className="w-3.5 h-3.5" /> {post.isHidden ? 'Unhide' : 'Hide'} Post
                  </button>
                </>
              )}
              {!isOwner && (
                <button
                  onClick={() => { setMenuOpen(false); setShowReportModal(true); }}
                  className="w-full flex items-center gap-2 px-3 py-2 text-sm text-white/70 hover:bg-white/5"
                >
                  <Flag className="w-3.5 h-3.5" /> Report Post
                </button>
              )}
            </div>
          )}
        </div>
      </div>

      {/* Achievement banner */}
      {post.type === 'achievement' && achievementMeta && (
        <div className={`flex items-center gap-2 px-3 py-2 rounded-lg bg-white/5 border border-white/10`}>
          <achievementMeta.icon className={`w-5 h-5 ${achievementMeta.color}`} />
          <span className={`font-bold text-sm ${achievementMeta.color}`}>{achievementMeta.label}</span>
          {post.taggedHoleNumber && <span className="text-xs text-muted-foreground ml-1">Hole {post.taggedHoleNumber}</span>}
        </div>
      )}

      {/* Body */}
      <p className="text-sm text-white/90 whitespace-pre-wrap">{post.body}</p>

      {/* Media */}
      {post.media.length > 0 && (
        <div className={`grid gap-1.5 ${post.media.length > 1 ? 'grid-cols-2' : 'grid-cols-1'}`}>
          {post.media.map((m, i) =>
            m.mimeType?.startsWith('video/') ? (
              <video
                key={i}
                src={m.url}
                controls
                preload="metadata"
                onTimeUpdate={handleVideoTimeUpdate}
                className="w-full rounded-lg object-cover max-h-96 bg-black"
              />
            ) : (
              <img
                key={i}
                src={m.url}
                alt=""
                className="w-full rounded-lg object-cover max-h-64"
              />
            )
          )}
        </div>
      )}

      {/* Hole tag */}
      {post.taggedHoleNumber && post.type !== 'achievement' && (
        <div className="inline-flex items-center gap-1.5 text-xs text-muted-foreground bg-white/5 px-2 py-1 rounded-full">
          <Flag className="w-3 h-3" /> Hole {post.taggedHoleNumber}
        </div>
      )}

      {/* Actions */}
      <div className="flex items-center gap-4 pt-1 border-t border-white/5">
        <button
          onClick={() => onReact(post.id, post.hasReacted)}
          className={`flex items-center gap-1.5 text-sm transition-colors ${post.hasReacted ? 'text-primary' : 'text-muted-foreground hover:text-primary'}`}
        >
          <Heart className={`w-4 h-4 ${post.hasReacted ? 'fill-primary' : ''}`} />
          <span>{post.reactionsCount}</span>
        </button>
        <button
          onClick={toggleComments}
          className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-white transition-colors"
        >
          <MessageCircle className="w-4 h-4" />
          <span>{post.commentsCount}</span>
        </button>
        {/* Task #708 — re-share button only for highlight-reel posts. Logs a
            'feed_share' engagement ping after the share sheet (or clipboard
            fallback) succeeds so producers can see in-feed re-shares. */}
        {post.reelId && post.media.some(m => m.mimeType?.startsWith('video/')) && (
          <button
            onClick={shareReelFromFeed}
            className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-white transition-colors"
          >
            <Share2 className="w-4 h-4" />
            <span>Share</span>
          </button>
        )}
      </div>

      {/* Comments section */}
      {showComments && (
        <div className="space-y-3 pt-2">
          {commentsLoading ? (
            <p className="text-xs text-muted-foreground text-center">Loading...</p>
          ) : comments.length === 0 ? (
            <p className="text-xs text-muted-foreground text-center">No comments yet. Be the first!</p>
          ) : (
            comments.map(c => (
              <div key={c.id} className="flex gap-2">
                <AvatarPlaceholder name={c.authorDisplayName || c.authorUsername} size="sm" />
                <div className="flex-1 bg-white/5 rounded-xl px-3 py-2">
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-semibold text-white">
                      {c.authorDisplayName || c.authorUsername || 'Member'}
                    </span>
                    <div className="flex items-center gap-1">
                      <span className="text-[10px] text-muted-foreground">{timeAgo(c.createdAt)}</span>
                      {(c.authorUserId === currentUserId || isAdmin) && (
                        <button
                          onClick={() => deleteComment(c.id)}
                          className="ml-1 text-muted-foreground hover:text-red-400"
                        >
                          <X className="w-3 h-3" />
                        </button>
                      )}
                    </div>
                  </div>
                  <p className="text-xs text-white/80 mt-0.5">{c.body}</p>
                </div>
              </div>
            ))
          )}
          {/* Comment input */}
          <div className="flex gap-2">
            <input
              value={commentText}
              onChange={e => setCommentText(e.target.value)}
              onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); submitComment(); }}}
              placeholder="Write a comment…"
              className="flex-1 text-sm bg-white/5 border border-white/10 rounded-xl px-3 py-2 text-white placeholder-muted-foreground outline-none focus:border-primary/50"
            />
            <Button
              size="sm"
              onClick={submitComment}
              disabled={!commentText.trim() || submittingComment}
              className="rounded-xl"
            >
              <Send className="w-3.5 h-3.5" />
            </Button>
          </div>
        </div>
      )}

      {/* Report modal */}
      {showReportModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60" onClick={() => setShowReportModal(false)}>
          <div className="bg-card border border-white/10 rounded-2xl p-6 w-full max-w-sm mx-4 space-y-4" onClick={e => e.stopPropagation()}>
            <div className="flex items-center justify-between">
              <h3 className="font-semibold text-white">Report Post</h3>
              <button onClick={() => setShowReportModal(false)}><X className="w-4 h-4 text-muted-foreground" /></button>
            </div>
            <div className="space-y-2">
              <label className="text-xs text-muted-foreground">Reason</label>
              <select
                value={reportReason}
                onChange={e => setReportReason(e.target.value)}
                className="w-full bg-white/5 border border-white/10 rounded-lg px-3 py-2 text-sm text-white"
              >
                <option value="inappropriate">Inappropriate</option>
                <option value="spam">Spam</option>
                <option value="offensive">Offensive</option>
                <option value="other">Other</option>
              </select>
            </div>
            <div className="space-y-2">
              <label className="text-xs text-muted-foreground">Additional notes (optional)</label>
              <textarea
                value={reportNotes}
                onChange={e => setReportNotes(e.target.value)}
                rows={2}
                className="w-full bg-white/5 border border-white/10 rounded-lg px-3 py-2 text-sm text-white resize-none"
                placeholder="Describe the issue…"
              />
            </div>
            <div className="flex justify-end gap-2">
              <Button variant="ghost" size="sm" onClick={() => setShowReportModal(false)}>Cancel</Button>
              <Button size="sm" onClick={submitReport}>Submit Report</Button>
            </div>
          </div>
        </div>
      )}
    </Card>
  );
}

function PostComposer({ orgId, isAdmin, onCreated }: { orgId: number; isAdmin: boolean; onCreated: (post: FeedPost) => void }) {
  const { toast } = useToast();
  const [body, setBody] = useState('');
  const [privacy, setPrivacy] = useState<'all_members' | 'followers_only'>('all_members');
  const [type, setType] = useState<'member_post' | 'club_announcement'>('member_post');
  const [holeNumber, setHoleNumber] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [expanded, setExpanded] = useState(false);

  async function submit() {
    if (!body.trim()) return;
    setSubmitting(true);
    try {
      const r = await fetch(API(`/organizations/${orgId}/feed/posts`), {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify({
          body,
          privacy,
          type,
          taggedHoleNumber: holeNumber ? parseInt(holeNumber) : undefined,
        }),
      });
      if (r.ok) {
        const post = await r.json();
        onCreated(post);
        setBody('');
        setHoleNumber('');
        setExpanded(false);
        toast({ title: 'Posted!', description: 'Your post is live.' });
      } else {
        toast({ title: 'Error', description: 'Failed to create post.', variant: 'destructive' });
      }
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <Card className="bg-card border-white/5 p-4 space-y-3">
      <div className="flex gap-3">
        <div className="w-10 h-10 rounded-full bg-primary/20 border border-primary/30 flex items-center justify-center flex-shrink-0">
          <span className="text-primary font-bold text-sm">You</span>
        </div>
        <textarea
          value={body}
          onChange={e => setBody(e.target.value)}
          onFocus={() => setExpanded(true)}
          placeholder="Share a round highlight, photo, or update…"
          rows={expanded ? 3 : 1}
          className="flex-1 bg-white/5 border border-white/10 rounded-xl px-3 py-2 text-sm text-white placeholder-muted-foreground resize-none outline-none focus:border-primary/50 transition-all"
        />
      </div>

      {expanded && (
        <div className="flex flex-wrap items-center gap-2 pl-13">
          {isAdmin && (
            <select
              value={type}
              onChange={e => setType(e.target.value as 'member_post' | 'club_announcement')}
              className="text-xs bg-white/5 border border-white/10 rounded-lg px-2 py-1 text-white"
            >
              <option value="member_post">Member Post</option>
              <option value="club_announcement">Club Announcement</option>
            </select>
          )}
          <select
            value={privacy}
            onChange={e => setPrivacy(e.target.value as 'all_members' | 'followers_only')}
            className="text-xs bg-white/5 border border-white/10 rounded-lg px-2 py-1 text-white"
          >
            <option value="all_members">All Members</option>
            <option value="followers_only">Followers Only</option>
          </select>
          <input
            value={holeNumber}
            onChange={e => setHoleNumber(e.target.value)}
            placeholder="Tag hole # (optional)"
            type="number"
            min={1} max={18}
            className="w-36 text-xs bg-white/5 border border-white/10 rounded-lg px-2 py-1 text-white placeholder-muted-foreground"
          />
          <div className="ml-auto flex gap-2">
            <Button variant="ghost" size="sm" onClick={() => { setExpanded(false); setBody(''); }}>Cancel</Button>
            <Button size="sm" onClick={submit} disabled={!body.trim() || submitting}>
              {submitting ? 'Posting…' : 'Post'}
            </Button>
          </div>
        </div>
      )}
    </Card>
  );
}

function ModerationPanel({ orgId }: { orgId: number }) {
  const { toast } = useToast();
  const [reports, setReports] = useState<Report[]>([]);
  const [loading, setLoading] = useState(true);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const r = await fetch(API(`/organizations/${orgId}/feed/moderation`), { credentials: 'include' });
      if (r.ok) setReports(await r.json());
    } finally {
      setLoading(false);
    }
  }, [orgId]);

  useEffect(() => { load(); }, [load]);

  async function resolve(reportId: number, action: string) {
    await fetch(API(`/organizations/${orgId}/feed/reports/${reportId}/resolve`), {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      credentials: 'include',
      body: JSON.stringify({ action }),
    });
    toast({ title: 'Report resolved' });
    setReports(prev => prev.filter(r => r.id !== reportId));
  }

  if (loading) return <div className="text-center text-muted-foreground py-8">Loading reports…</div>;

  return (
    <div className="space-y-3">
      {reports.length === 0 ? (
        <Card className="bg-card border-white/5 p-8 text-center">
          <Shield className="w-8 h-8 text-emerald-500 mx-auto mb-2" />
          <p className="text-sm text-muted-foreground">No pending reports. Feed looks clean!</p>
        </Card>
      ) : (
        reports.map(r => (
          <Card key={r.id} className="bg-card border-white/5 p-4 space-y-3">
            <div className="flex items-start justify-between gap-2">
              <div className="space-y-1">
                <div className="flex items-center gap-2">
                  <AlertTriangle className="w-4 h-4 text-amber-400" />
                  <span className="text-sm font-semibold text-white">
                    {r.reason.charAt(0).toUpperCase() + r.reason.slice(1)} report
                  </span>
                  <Badge className="text-[10px] bg-amber-500/20 text-amber-300 border-amber-500/30">pending</Badge>
                </div>
                <p className="text-xs text-muted-foreground">
                  Reported by {r.reporterDisplayName || r.reporterUsername || 'Anonymous'} · {timeAgo(r.createdAt)}
                </p>
                {r.notes && <p className="text-xs text-white/60">"{r.notes}"</p>}
              </div>
            </div>
            {r.post && (
              <div className="bg-white/5 rounded-lg px-3 py-2 border-l-2 border-amber-500/50">
                <p className="text-xs text-white/80 line-clamp-2">{r.post.body}</p>
                {r.post.isHidden && <Badge className="mt-1 text-[10px] bg-white/10 text-white/50">Already hidden</Badge>}
              </div>
            )}
            <div className="flex gap-2">
              <Button size="sm" variant="ghost" onClick={() => resolve(r.id, 'dismiss')} className="text-xs">
                Dismiss
              </Button>
              {r.postId && (
                <Button size="sm" variant="destructive" onClick={() => resolve(r.id, 'hide')} className="text-xs">
                  Hide Post
                </Button>
              )}
            </div>
          </Card>
        ))
      )}
    </div>
  );
}

export default function FeedPage() {
  const { data: user } = useGetMe();
  const { activeOrgId: orgId } = useActiveOrgContext();
  const { toast } = useToast();

  const [posts, setPosts] = useState<FeedPost[]>([]);
  const [loading, setLoading] = useState(true);
  const [loadingMore, setLoadingMore] = useState(false);
  const [hasMore, setHasMore] = useState(false);
  const [nextCursor, setNextCursor] = useState<string | null>(null);
  const [tab, setTab] = useState<'feed' | 'moderation'>('feed');

  const isAdmin = ['org_admin', 'super_admin', 'tournament_director'].includes(user?.role ?? '');

  async function loadFeed(cursor?: string) {
    if (!orgId) return;
    const isFirst = !cursor;
    if (isFirst) setLoading(true); else setLoadingMore(true);
    try {
      const url = new URL(API(`/organizations/${orgId}/feed`), window.location.origin);
      if (cursor) url.searchParams.set('cursor', cursor);
      url.searchParams.set('limit', '20');
      const r = await fetch(url.toString(), { credentials: 'include' });
      if (r.ok) {
        const data = await r.json();
        if (isFirst) setPosts(data.posts);
        else setPosts(prev => [...prev, ...data.posts]);
        setHasMore(data.hasMore);
        setNextCursor(data.nextCursor);
      }
    } finally {
      setLoading(false);
      setLoadingMore(false);
    }
  }

  useEffect(() => { loadFeed(); }, [orgId]);

  function handlePostCreated(post: FeedPost) {
    setPosts(prev => [post, ...prev]);
  }

  async function handleDelete(id: number) {
    if (!confirm('Delete this post?')) return;
    if (!orgId) return;
    const r = await fetch(API(`/organizations/${orgId}/feed/posts/${id}`), {
      method: 'DELETE', credentials: 'include',
    });
    if (r.ok) {
      setPosts(prev => prev.filter(p => p.id !== id));
      toast({ title: 'Post deleted' });
    }
  }

  async function handleReact(id: number, wasReacted: boolean) {
    if (!orgId) return;
    const r = await fetch(API(`/organizations/${orgId}/feed/posts/${id}/react`), {
      method: 'POST', credentials: 'include',
    });
    if (r.ok) {
      const { reacted } = await r.json();
      setPosts(prev => prev.map(p => p.id === id
        ? { ...p, hasReacted: reacted, reactionsCount: p.reactionsCount + (reacted ? 1 : -1) }
        : p
      ));
    }
  }

  async function handlePin(id: number) {
    if (!orgId) return;
    const r = await fetch(API(`/organizations/${orgId}/feed/posts/${id}/pin`), {
      method: 'POST', credentials: 'include',
    });
    if (r.ok) {
      const { isPinned } = await r.json();
      setPosts(prev => prev.map(p => p.id === id ? { ...p, isPinned } : p));
    }
  }

  async function handleHide(id: number) {
    if (!orgId) return;
    const r = await fetch(API(`/organizations/${orgId}/feed/posts/${id}/hide`), {
      method: 'POST', credentials: 'include',
    });
    if (r.ok) {
      setPosts(prev => prev.filter(p => p.id !== id));
      toast({ title: 'Post hidden' });
    }
  }

  if (!orgId) {
    return (
      <div className="flex items-center justify-center h-48">
        <p className="text-muted-foreground">No organization selected</p>
      </div>
    );
  }

  return (
    <div className="p-6 max-w-2xl mx-auto space-y-4">
      <div className="flex items-center justify-between mb-2">
        <div>
          <h1 className="text-2xl font-bold text-white">Club Feed</h1>
          <p className="text-sm text-muted-foreground">Activity, highlights & announcements</p>
        </div>
      </div>

      {isAdmin ? (
        <Tabs value={tab} onValueChange={v => setTab(v as 'feed' | 'moderation')}>
          <TabsList className="bg-white/5 border border-white/10">
            <TabsTrigger value="feed">Feed</TabsTrigger>
            <TabsTrigger value="moderation" className="flex items-center gap-1.5">
              <Shield className="w-3.5 h-3.5" /> Moderation
            </TabsTrigger>
          </TabsList>

          <TabsContent value="feed" className="space-y-4 mt-4">
            <PostComposer orgId={orgId} isAdmin={isAdmin} onCreated={post => handlePostCreated(post as FeedPost)} />
            {loading ? (
              <div className="space-y-3">
                {[1, 2, 3].map(i => (
                  <div key={i} className="h-32 bg-card border border-white/5 rounded-xl animate-pulse" />
                ))}
              </div>
            ) : posts.length === 0 ? (
              <Card className="bg-card border-white/5 p-12 text-center">
                <MessageCircle className="w-10 h-10 text-muted-foreground mx-auto mb-3 opacity-30" />
                <p className="text-white/60">No posts yet. Be the first to share something!</p>
              </Card>
            ) : (
              <>
                {posts.map(p => (
                  <PostCard
                    key={p.id}
                    post={p}
                    orgId={orgId}
                    currentUserId={user?.id as number | undefined}
                    isAdmin={isAdmin}
                    onDelete={handleDelete}
                    onReact={handleReact}
                    onPin={handlePin}
                    onHide={handleHide}
                  />
                ))}
                {hasMore && (
                  <Button
                    variant="ghost"
                    className="w-full"
                    onClick={() => loadFeed(nextCursor ?? undefined)}
                    disabled={loadingMore}
                  >
                    {loadingMore ? 'Loading…' : 'Load more'}
                    <ChevronDown className="w-4 h-4 ml-1" />
                  </Button>
                )}
              </>
            )}
          </TabsContent>

          <TabsContent value="moderation" className="mt-4">
            <ModerationPanel orgId={orgId} />
          </TabsContent>
        </Tabs>
      ) : (
        <div className="space-y-4">
          <PostComposer orgId={orgId} isAdmin={false} onCreated={post => handlePostCreated(post as FeedPost)} />
          {loading ? (
            <div className="space-y-3">
              {[1, 2, 3].map(i => (
                <div key={i} className="h-32 bg-card border border-white/5 rounded-xl animate-pulse" />
              ))}
            </div>
          ) : posts.length === 0 ? (
            <Card className="bg-card border-white/5 p-12 text-center">
              <MessageCircle className="w-10 h-10 text-muted-foreground mx-auto mb-3 opacity-30" />
              <p className="text-white/60">No posts yet. Share your round highlight!</p>
            </Card>
          ) : (
            <>
              {posts.map(p => (
                <PostCard
                  key={p.id}
                  post={p}
                  orgId={orgId}
                  currentUserId={user?.id as number | undefined}
                  isAdmin={false}
                  onDelete={handleDelete}
                  onReact={handleReact}
                  onPin={handlePin}
                  onHide={handleHide}
                />
              ))}
              {hasMore && (
                <Button
                  variant="ghost"
                  className="w-full"
                  onClick={() => loadFeed(nextCursor ?? undefined)}
                  disabled={loadingMore}
                >
                  {loadingMore ? 'Loading…' : 'Load more'}
                  <ChevronDown className="w-4 h-4 ml-1" />
                </Button>
              )}
            </>
          )}
        </div>
      )}
    </div>
  );
}
