import React, { useCallback, useEffect, useRef, useState } from "react";
import {
  FlatList,
  Image,
  Modal,
  Platform,
  Pressable,
  RefreshControl,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  TouchableOpacity,
  View,
} from "react-native";
import { LoadingSpinner } from "@/components/LoadingSpinner";
import { Feather, Ionicons } from "@expo/vector-icons";
import { Video, ResizeMode, type AVPlaybackStatus } from "expo-av";
import * as Sharing from "expo-sharing";
import { File, Paths } from "expo-file-system";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { useFocusEffect, router as expoRouter } from "expo-router";
import { useAuth } from "@/context/auth";
import { useMoreBadges } from "@/context/moreBadges";
import { FollowButton } from "@/components/FollowButton";
import { useFolloweeIds } from "@/hooks/useFolloweeIds";
import Colors from "@/constants/colors";
import { getLocale } from "@/i18n";
import { formatRelativeTime } from "@/i18n/relativeTime";

const BASE_URL = process.env.EXPO_PUBLIC_DOMAIN
  ? `https://${process.env.EXPO_PUBLIC_DOMAIN}`
  : "";

function API(path: string) {
  return `${BASE_URL}/api${path}`;
}

/** Normalize a media URL: relative paths get the API base origin prefixed
 *  so React Native's Video/Image components can resolve them. */
function absUrl(u: string | null | undefined): string {
  if (!u) return "";
  if (/^https?:\/\//i.test(u)) return u;
  return `${BASE_URL}${u.startsWith("/") ? "" : "/"}${u}`;
}

function timeAgo(dateStr: string) {
  const diff = (Date.now() - new Date(dateStr).getTime()) / 1000;
  // <24h: defer to the shared `formatRelativeTime` helper so every
  // supported locale gets correctly-translated copy via
  // Intl.RelativeTimeFormat (matches the home-tab `timeAgo` and the
  // committee case detail screen migrated in Task #1659). Older posts
  // keep their absolute "Apr 14" calendar label for fast scanning.
  if (diff < 86400) return formatRelativeTime(dateStr);
  return new Date(dateStr).toLocaleDateString(getLocale(), { day: "numeric", month: "short" });
}

type PostType = "member_post" | "achievement" | "club_announcement";

interface FeedPost {
  id: number;
  type: PostType;
  body: string;
  privacy: "all_members" | "followers_only";
  isPinned: boolean;
  taggedHoleNumber: number | null;
  achievementType: string | null;
  reactionsCount: number;
  commentsCount: number;
  createdAt: string;
  authorUserId: number | null;
  authorDisplayName: string | null;
  authorUsername: string | null;
  authorProfileImage: string | null;
  media: { url: string; mimeType: string; sortOrder: number }[];
  hasReacted: boolean;
  // Task #708 — set when this post was generated by posting a highlight reel
  // to the feed. Lets us fire view + feed_share engagement pings against the
  // /portal/highlights/:id/events endpoint.
  reelId: number | null;
}

interface Comment {
  id: number;
  body: string;
  createdAt: string;
  authorDisplayName: string | null;
  authorUsername: string | null;
}

const ACHIEVEMENT_META: Record<string, { emoji: string; label: string; color: string }> = {
  hole_in_one: { emoji: "⭐", label: "Hole in One!", color: "#F59E0B" },
  eagle: { emoji: "🦅", label: "Eagle", color: "#10B981" },
  personal_best: { emoji: "🏆", label: "Personal Best", color: "#3B82F6" },
  tournament_win: { emoji: "🥇", label: "Tournament Win", color: Colors.primary },
};

function Avatar({ name, imageUrl, size = 40 }: { name: string | null; imageUrl?: string | null; size?: number }) {
  const initials = name
    ? name.split(" ").map(n => n[0]).join("").slice(0, 2).toUpperCase()
    : "?";
  if (imageUrl) {
    return (
      <Image
        source={{ uri: imageUrl }}
        style={{ width: size, height: size, borderRadius: size / 2 }}
      />
    );
  }
  return (
    <View style={[styles.avatar, { width: size, height: size, borderRadius: size / 2 }]}>
      <Text style={[styles.avatarText, { fontSize: size * 0.35 }]}>{initials}</Text>
    </View>
  );
}

export function PostCard({
  post,
  orgId,
  token,
  currentUserId,
  isAdmin,
  followeeIds,
  onDelete,
  onReact,
}: {
  post: FeedPost;
  orgId: number;
  token: string;
  currentUserId: number | null;
  isAdmin: boolean;
  followeeIds: number[];
  onDelete: (id: number) => void;
  onReact: (id: number, reacted: boolean) => void;
}) {
  const [showComments, setShowComments] = useState(false);
  const [comments, setComments] = useState<Comment[]>([]);
  const [commentText, setCommentText] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  const [reportModal, setReportModal] = useState(false);
  const [reportReason, setReportReason] = useState("inappropriate");
  // Task #708 — once a viewer watches the reel for ≥VIEW_THRESHOLD_MS we fire
  // a single 'view' engagement ping. The flag prevents repeat pings if the
  // viewer scrubs / replays inside the same render of this card.
  // Task #1014 — must be a ref (not state) so back-to-back synchronous
  // onPlaybackStatusUpdate callbacks (which expo-av can deliver in a
  // single tick after a stall recovers) don't all observe a stale
  // pre-commit `false` and each fire their own ping.
  const viewLoggedRef = useRef(false);

  const headers = {
    "Content-Type": "application/json",
    ...(token ? { Authorization: `Bearer ${token}` } : {}),
  };

  // Task #708 — fire-and-forget engagement ping. We swallow errors so a flaky
  // network never disrupts feed playback or the share UX.
  const logReelEngagement = (type: "view" | "feed_share") => {
    if (!post.reelId) return;
    try {
      fetch(API(`/portal/highlights/${post.reelId}/events`), {
        method: "POST",
        headers,
        body: JSON.stringify({ type, source: "mobile_feed" }),
      }).catch(() => { /* best-effort analytics */ });
    } catch { /* best-effort analytics */ }
  };

  // 2s of cumulative playback is the "watched" threshold (matches the task
  // description). We use the playback positionMillis from expo-av rather than
  // wall-clock so paused/buffering time doesn't count.
  const VIEW_THRESHOLD_MS = 2000;
  const onVideoStatus = (status: AVPlaybackStatus) => {
    if (viewLoggedRef.current || !post.reelId) return;
    if (!("isLoaded" in status) || !status.isLoaded) return;
    if (status.positionMillis >= VIEW_THRESHOLD_MS) {
      viewLoggedRef.current = true;
      logReelEngagement("view");
    }
  };

  // Task #708 — native sharing on iOS/Android needs a *local* file URI;
  // handing Sharing.shareAsync a remote https:// URL fails silently on
  // most devices. Mirror what `app/highlights.tsx` does: download the
  // reel into the cache dir first, then hand the local URI to the share
  // sheet, and only log the 'feed_share' engagement ping once the share
  // sheet successfully opened.
  const shareReelFromFeed = async () => {
    if (!post.reelId) return;
    const videoMedia = post.media.find(m => m.mimeType?.startsWith("video/"));
    if (!videoMedia) return;
    try {
      const available = await Sharing.isAvailableAsync();
      if (!available) return;
      const remote = absUrl(videoMedia.url);
      const fileName = `feed_reel_${post.reelId}.mp4`;
      const target = new File(Paths.cache, fileName);
      if (target.exists) {
        try { target.delete(); } catch { /* ignore */ }
      }
      const downloaded = await File.downloadFileAsync(remote, target);
      await Sharing.shareAsync(downloaded.uri, {
        mimeType: "video/mp4",
        dialogTitle: post.body || "Highlight reel",
        UTI: "public.mpeg-4",
      });
      logReelEngagement("feed_share");
    } catch {
      /* user cancelled, download failed, or share unsupported — no-op */
    }
  };

  async function loadComments() {
    try {
      const r = await fetch(API(`/organizations/${orgId}/feed/posts/${post.id}/comments`), { headers });
      if (r.ok) setComments(await r.json());
    } catch {}
  }

  function toggleComments() {
    if (!showComments) loadComments();
    setShowComments(v => !v);
  }

  async function submitComment() {
    if (!commentText.trim()) return;
    setSubmitting(true);
    try {
      const r = await fetch(API(`/organizations/${orgId}/feed/posts/${post.id}/comments`), {
        method: "POST", headers, body: JSON.stringify({ body: commentText }),
      });
      if (r.ok) {
        const c = await r.json();
        setComments(prev => [...prev, c]);
        setCommentText("");
      }
    } finally { setSubmitting(false); }
  }

  async function submitReport() {
    try {
      await fetch(API(`/organizations/${orgId}/feed/posts/${post.id}/report`), {
        method: "POST", headers, body: JSON.stringify({ reason: reportReason }),
      });
      setReportModal(false);
    } catch {}
  }

  const achieveMeta = post.achievementType ? ACHIEVEMENT_META[post.achievementType] : null;

  const isOwner = post.authorUserId === currentUserId;

  return (
    <View style={styles.card}>
      {/* Header */}
      <View style={styles.cardHeader}>
        <TouchableOpacity
          onPress={() => post.authorUserId && expoRouter.push({
            pathname: "/member/[userId]" as never,
            params: {
              userId: String(post.authorUserId),
              displayName: post.authorDisplayName || post.authorUsername || "",
              avatar: post.authorProfileImage || "",
            },
          } as never)}
          disabled={!post.authorUserId}
          activeOpacity={0.7}
        >
          <Avatar
            name={post.authorDisplayName || post.authorUsername}
            imageUrl={post.authorProfileImage}
          />
        </TouchableOpacity>
        <View style={styles.cardHeaderText}>
          <View style={styles.cardHeaderRow}>
            <Text style={styles.authorName}>
              {post.authorDisplayName || post.authorUsername || "Club"}
            </Text>
            {post.type === "club_announcement" && (
              <View style={styles.announceBadge}>
                <Text style={styles.announceBadgeText}>📌 Announcement</Text>
              </View>
            )}
            {post.type === "achievement" && achieveMeta && (
              <View style={[styles.announceBadge, { borderColor: achieveMeta.color + "50" }]}>
                <Text style={[styles.announceBadgeText, { color: achieveMeta.color }]}>
                  {achieveMeta.emoji} {achieveMeta.label}
                </Text>
              </View>
            )}
          </View>
          <Text style={styles.timeText}>{timeAgo(post.createdAt)}</Text>
        </View>
        {post.authorUserId && !isOwner && (
          <FollowButton
            userId={post.authorUserId}
            initialFollowing={followeeIds.includes(post.authorUserId)}
          />
        )}
        <TouchableOpacity onPress={() => setMenuOpen(true)} style={styles.menuBtn}>
          <Feather name="more-horizontal" size={18} color={Colors.textSecondary} />
        </TouchableOpacity>
      </View>

      {/* Achievement banner */}
      {post.type === "achievement" && achieveMeta && (
        <View style={[styles.achieveBanner, { borderLeftColor: achieveMeta.color }]}>
          <Text style={[styles.achieveText, { color: achieveMeta.color }]}>
            {achieveMeta.emoji} {achieveMeta.label}
            {post.taggedHoleNumber ? `  ·  Hole ${post.taggedHoleNumber}` : ""}
          </Text>
        </View>
      )}

      {/* Body */}
      <Text style={styles.postBody}>{post.body}</Text>

      {/* Media */}
      {post.media.length > 0 && (
        <View style={styles.mediaGrid}>
          {post.media.slice(0, 4).map((m, i) =>
            m.mimeType?.startsWith("video/") ? (
              <Video
                key={i}
                source={{ uri: absUrl(m.url) }}
                style={[
                  styles.mediaImage,
                  { height: 240 },
                  post.media.length > 1 && { width: "49%" },
                ]}
                useNativeControls
                resizeMode={ResizeMode.COVER}
                isLooping={false}
                onPlaybackStatusUpdate={onVideoStatus}
              />
            ) : (
              <Image
                key={i}
                source={{ uri: absUrl(m.url) }}
                style={[
                  styles.mediaImage,
                  post.media.length > 1 && { width: "49%" },
                ]}
                resizeMode="cover"
              />
            ),
          )}
        </View>
      )}

      {/* Hole tag */}
      {post.taggedHoleNumber && post.type !== "achievement" && (
        <View style={styles.holeTag}>
          <Feather name="flag" size={11} color={Colors.textSecondary} />
          <Text style={styles.holeTagText}>Hole {post.taggedHoleNumber}</Text>
        </View>
      )}

      {/* Action bar */}
      <View style={styles.actionBar}>
        <TouchableOpacity onPress={() => onReact(post.id, post.hasReacted)} style={styles.actionBtn}>
          <Feather
            name="heart"
            size={17}
            color={post.hasReacted ? Colors.primary : Colors.textSecondary}
          />
          <Text style={[styles.actionText, post.hasReacted && { color: Colors.primary }]}>
            {post.reactionsCount}
          </Text>
        </TouchableOpacity>
        <TouchableOpacity onPress={toggleComments} style={styles.actionBtn}>
          <Feather name="message-circle" size={17} color={Colors.textSecondary} />
          <Text style={styles.actionText}>{post.commentsCount}</Text>
        </TouchableOpacity>
        {/* Task #708 — re-share button only for posts that are highlight reels.
            Fires a 'feed_share' engagement ping after the system share sheet
            hands the clip off so producers can see in-feed re-shares. */}
        {post.reelId && post.media.some(m => m.mimeType?.startsWith("video/")) && (
          <TouchableOpacity onPress={shareReelFromFeed} style={styles.actionBtn}>
            <Feather name="share-2" size={17} color={Colors.textSecondary} />
            <Text style={styles.actionText}>Share</Text>
          </TouchableOpacity>
        )}
      </View>

      {/* Comments */}
      {showComments && (
        <View style={styles.commentsSection}>
          {comments.length === 0 ? (
            <Text style={styles.noComments}>No comments yet.</Text>
          ) : (
            comments.map(c => (
              <View key={c.id} style={styles.commentRow}>
                <Avatar name={c.authorDisplayName || c.authorUsername} size={28} />
                <View style={styles.commentBubble}>
                  <Text style={styles.commentAuthor}>
                    {c.authorDisplayName || c.authorUsername || "Member"}
                  </Text>
                  <Text style={styles.commentBody}>{c.body}</Text>
                </View>
              </View>
            ))
          )}
          <View style={styles.commentInput}>
            <TextInput
              value={commentText}
              onChangeText={setCommentText}
              placeholder="Add a comment…"
              placeholderTextColor={Colors.textSecondary}
              style={styles.commentTextInput}
              multiline={false}
              onSubmitEditing={submitComment}
              returnKeyType="send"
            />
            <TouchableOpacity
              onPress={submitComment}
              disabled={!commentText.trim() || submitting}
              style={styles.commentSend}
            >
              <Feather name="send" size={16} color={Colors.primary} />
            </TouchableOpacity>
          </View>
        </View>
      )}

      {/* Context menu modal */}
      <Modal visible={menuOpen} transparent animationType="fade" onRequestClose={() => setMenuOpen(false)}>
        <Pressable style={styles.modalOverlay} onPress={() => setMenuOpen(false)}>
          <View style={styles.menuSheet}>
            {(isOwner || isAdmin) && (
              <TouchableOpacity
                style={styles.menuItem}
                onPress={() => { setMenuOpen(false); onDelete(post.id); }}
              >
                <Feather name="trash-2" size={16} color="#EF4444" />
                <Text style={[styles.menuItemText, { color: "#EF4444" }]}>Delete Post</Text>
              </TouchableOpacity>
            )}
            {!isOwner && (
              <TouchableOpacity
                style={styles.menuItem}
                onPress={() => { setMenuOpen(false); setReportModal(true); }}
              >
                <Feather name="flag" size={16} color={Colors.textSecondary} />
                <Text style={styles.menuItemText}>Report Post</Text>
              </TouchableOpacity>
            )}
            <TouchableOpacity style={styles.menuItem} onPress={() => setMenuOpen(false)}>
              <Feather name="x" size={16} color={Colors.textSecondary} />
              <Text style={styles.menuItemText}>Cancel</Text>
            </TouchableOpacity>
          </View>
        </Pressable>
      </Modal>

      {/* Report modal */}
      <Modal visible={reportModal} transparent animationType="slide" onRequestClose={() => setReportModal(false)}>
        <Pressable style={styles.modalOverlay} onPress={() => setReportModal(false)}>
          <View style={styles.reportSheet} onStartShouldSetResponder={() => true}>
            <Text style={styles.reportTitle}>Report Post</Text>
            {["inappropriate", "spam", "offensive", "other"].map(r => (
              <TouchableOpacity
                key={r}
                style={[styles.reportOption, reportReason === r && styles.reportOptionSelected]}
                onPress={() => setReportReason(r)}
              >
                <Feather
                  name={reportReason === r ? "check-circle" : "circle"}
                  size={16}
                  color={reportReason === r ? Colors.primary : Colors.textSecondary}
                />
                <Text style={[styles.reportOptionText, reportReason === r && { color: Colors.primary }]}>
                  {r.charAt(0).toUpperCase() + r.slice(1)}
                </Text>
              </TouchableOpacity>
            ))}
            <View style={styles.reportButtons}>
              <TouchableOpacity onPress={() => setReportModal(false)} style={styles.reportCancelBtn}>
                <Text style={styles.reportCancelText}>Cancel</Text>
              </TouchableOpacity>
              <TouchableOpacity onPress={submitReport} style={styles.reportSubmitBtn}>
                <Text style={styles.reportSubmitText}>Report</Text>
              </TouchableOpacity>
            </View>
          </View>
        </Pressable>
      </Modal>
    </View>
  );
}

function Composer({
  orgId,
  token,
  isAdmin,
  onCreated,
}: {
  orgId: number;
  token: string;
  isAdmin: boolean;
  onCreated: (post: FeedPost) => void;
}) {
  const [body, setBody] = useState("");
  const [privacy, setPrivacy] = useState<"all_members" | "followers_only">("all_members");
  const [type, setType] = useState<"member_post" | "club_announcement">("member_post");
  const [holeNumber, setHoleNumber] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [expanded, setExpanded] = useState(false);

  const headers = {
    "Content-Type": "application/json",
    ...(token ? { Authorization: `Bearer ${token}` } : {}),
  };

  async function submit() {
    if (!body.trim()) return;
    setSubmitting(true);
    try {
      const r = await fetch(API(`/organizations/${orgId}/feed/posts`), {
        method: "POST",
        headers,
        body: JSON.stringify({
          body,
          privacy,
          type,
          taggedHoleNumber: holeNumber ? parseInt(holeNumber) : undefined,
        }),
      });
      if (r.ok) {
        const post = await r.json();
        onCreated(post);
        setBody("");
        setHoleNumber("");
        setExpanded(false);
      }
    } finally { setSubmitting(false); }
  }

  return (
    <View style={styles.composer}>
      <TextInput
        value={body}
        onChangeText={setBody}
        onFocus={() => setExpanded(true)}
        placeholder="Share a round highlight, photo, or update…"
        placeholderTextColor={Colors.textSecondary}
        style={[styles.composerInput, expanded && { height: 80 }]}
        multiline
      />
      {expanded && (
        <View style={styles.composerActions}>
          <TextInput
            value={holeNumber}
            onChangeText={setHoleNumber}
            placeholder="Hole # (opt.)"
            placeholderTextColor={Colors.textSecondary}
            keyboardType="number-pad"
            style={styles.holeInput}
          />
          <TouchableOpacity
            onPress={() => setPrivacy(p => p === "all_members" ? "followers_only" : "all_members")}
            style={styles.privacyBtn}
          >
            <Feather
              name={privacy === "all_members" ? "users" : "user"}
              size={14}
              color={Colors.textSecondary}
            />
            <Text style={styles.privacyText}>
              {privacy === "all_members" ? "All" : "Followers"}
            </Text>
          </TouchableOpacity>
          <View style={{ flex: 1 }} />
          <TouchableOpacity onPress={() => { setExpanded(false); setBody(""); }} style={styles.cancelBtn}>
            <Text style={styles.cancelText}>Cancel</Text>
          </TouchableOpacity>
          <TouchableOpacity
            onPress={submit}
            disabled={!body.trim() || submitting}
            style={[styles.postBtn, (!body.trim() || submitting) && { opacity: 0.5 }]}
          >
            {submitting
              ? <LoadingSpinner size="small" color="#fff" />
              : <Text style={styles.postBtnText}>Post</Text>
            }
          </TouchableOpacity>
        </View>
      )}
    </View>
  );
}

export default function FeedScreen() {
  const insets = useSafeAreaInsets();
  const { token, user, orgId } = useAuth();
  const { markFeedSeen } = useMoreBadges();

  const [posts, setPosts] = useState<FeedPost[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [loadingMore, setLoadingMore] = useState(false);
  const [hasMore, setHasMore] = useState(false);
  const [nextCursor, setNextCursor] = useState<string | null>(null);
  // Pre-fetched followee IDs so the FollowButton on each post hydrates as
  // "Following" instead of flashing "Follow" first (Task #1227). Shared
  // with the public member profile screen via @/hooks/useFolloweeIds.
  const { followeeIds, refresh: refreshFollowees } = useFolloweeIds(token);

  const isAdmin = ["org_admin", "super_admin", "tournament_director"].includes(
    (user as any)?.role ?? ""
  );
  const currentUserId = (user as any)?.id ?? null;

  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    ...(token ? { Authorization: `Bearer ${token}` } : {}),
  };

  async function fetchFeed(cursor?: string) {
    if (!orgId) return;
    const url = new URL(API(`/organizations/${orgId}/feed`));
    if (cursor) url.searchParams.set("cursor", cursor);
    url.searchParams.set("limit", "20");
    const r = await fetch(url.toString(), { headers });
    if (r.ok) {
      const data = await r.json();
      return data;
    }
    return null;
  }

  async function loadInitial() {
    setLoading(true);
    try {
      const data = await fetchFeed();
      if (data) {
        setPosts(data.posts);
        setHasMore(data.hasMore);
        setNextCursor(data.nextCursor);
      }
    } finally { setLoading(false); }
  }

  async function loadMore() {
    if (!hasMore || loadingMore || !nextCursor) return;
    setLoadingMore(true);
    try {
      const data = await fetchFeed(nextCursor);
      if (data) {
        setPosts(prev => [...prev, ...data.posts]);
        setHasMore(data.hasMore);
        setNextCursor(data.nextCursor);
      }
    } finally { setLoadingMore(false); }
  }

  async function handleRefresh() {
    setRefreshing(true);
    try { await loadInitial(); } finally { setRefreshing(false); }
  }

  useFocusEffect(useCallback(() => {
    loadInitial();
    // Re-pull followee IDs whenever the feed regains focus so the
    // FollowButton state stays accurate after the user follows someone
    // from another screen (e.g. the member profile).
    refreshFollowees();
    // The user is now actually looking at the feed, so collapse the
    // "new posts since last visit" badge surfaced by the More menu.
    void markFeedSeen();
  }, [orgId, markFeedSeen, refreshFollowees]));

  async function handleDelete(id: number) {
    if (!orgId) return;
    await fetch(API(`/organizations/${orgId}/feed/posts/${id}`), {
      method: "DELETE", headers,
    });
    setPosts(prev => prev.filter(p => p.id !== id));
  }

  async function handleReact(id: number, wasReacted: boolean) {
    if (!orgId) return;
    const r = await fetch(API(`/organizations/${orgId}/feed/posts/${id}/react`), {
      method: "POST", headers,
    });
    if (r.ok) {
      const { reacted } = await r.json();
      setPosts(prev => prev.map(p => p.id === id
        ? { ...p, hasReacted: reacted, reactionsCount: p.reactionsCount + (reacted ? 1 : -1) }
        : p
      ));
    }
  }

  const renderItem = ({ item }: { item: FeedPost }) => (
    <PostCard
      post={item}
      orgId={orgId as number}
      token={token || ""}
      currentUserId={currentUserId}
      isAdmin={isAdmin}
      followeeIds={followeeIds}
      onDelete={handleDelete}
      onReact={handleReact}
    />
  );

  return (
    <View style={[styles.container, { paddingTop: insets.top }]}>
      {/* Header */}
      <View style={styles.header}>
        <Text style={styles.headerTitle}>Club Feed</Text>
        <Text style={styles.headerSub}>Highlights & announcements</Text>
      </View>

      {loading ? (
        <View style={styles.loadingCenter}>
          <LoadingSpinner size="large" color={Colors.primary} />
        </View>
      ) : (
        <FlatList
          data={posts}
          keyExtractor={item => String(item.id)}
          renderItem={renderItem}
          contentContainerStyle={styles.list}
          ItemSeparatorComponent={() => <View style={{ height: 12 }} />}
          ListHeaderComponent={
            <Composer
              orgId={orgId as number}
              token={token || ""}
              isAdmin={isAdmin}
              onCreated={post => setPosts(prev => [post, ...prev])}
            />
          }
          ListEmptyComponent={
            <View style={styles.emptyState}>
              <Feather name="message-circle" size={40} color={Colors.textSecondary} style={{ opacity: 0.3 }} />
              <Text style={styles.emptyText}>No posts yet.</Text>
              <Text style={styles.emptySubText}>Share a round highlight to get started!</Text>
            </View>
          }
          ListFooterComponent={
            hasMore ? (
              <TouchableOpacity style={styles.loadMoreBtn} onPress={loadMore} disabled={loadingMore}>
                {loadingMore
                  ? <LoadingSpinner size="small" color={Colors.primary} />
                  : <Text style={styles.loadMoreText}>Load more</Text>
                }
              </TouchableOpacity>
            ) : null
          }
          refreshControl={
            <RefreshControl
              refreshing={refreshing}
              onRefresh={handleRefresh}
              tintColor={Colors.primary}
            />
          }
        />
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  header: { paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: Colors.border },
  headerTitle: { fontSize: 22, fontWeight: "700", color: Colors.text },
  headerSub: { fontSize: 12, color: Colors.textSecondary, marginTop: 1 },
  list: { padding: 12, paddingBottom: 80 },
  loadingCenter: { flex: 1, alignItems: "center", justifyContent: "center" },

  // Composer
  composer: {
    backgroundColor: Colors.card,
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: Colors.border,
    marginBottom: 12,
  },
  composerInput: {
    color: Colors.text,
    fontSize: 14,
    height: 40,
    textAlignVertical: "top",
  },
  composerActions: { flexDirection: "row", alignItems: "center", gap: 8, marginTop: 8 },
  holeInput: {
    width: 80,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Colors.border,
    paddingHorizontal: 8,
    paddingVertical: 4,
    color: Colors.text,
    fontSize: 12,
  },
  privacyBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Colors.border,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  privacyText: { color: Colors.textSecondary, fontSize: 11 },
  cancelBtn: { paddingHorizontal: 10, paddingVertical: 6 },
  cancelText: { color: Colors.textSecondary, fontSize: 13 },
  postBtn: {
    backgroundColor: Colors.primary,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 6,
  },
  postBtnText: { color: "#fff", fontWeight: "700", fontSize: 13 },

  // Card
  card: {
    backgroundColor: Colors.card,
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  cardHeader: { flexDirection: "row", alignItems: "flex-start", gap: 10, marginBottom: 10 },
  cardHeaderText: { flex: 1 },
  cardHeaderRow: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 6 },
  authorName: { color: Colors.text, fontWeight: "600", fontSize: 14 },
  announceBadge: {
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "rgba(201,168,76,0.3)",
    paddingHorizontal: 6,
    paddingVertical: 1,
  },
  announceBadgeText: { color: Colors.primary, fontSize: 10, fontWeight: "600" },
  timeText: { color: Colors.textSecondary, fontSize: 11, marginTop: 1 },
  menuBtn: { padding: 2 },

  achieveBanner: {
    borderLeftWidth: 3,
    borderLeftColor: Colors.primary,
    paddingLeft: 10,
    paddingVertical: 6,
    marginBottom: 8,
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 4,
  },
  achieveText: { fontWeight: "700", fontSize: 13 },

  postBody: { color: Colors.text, fontSize: 14, lineHeight: 20, marginBottom: 8 },

  mediaGrid: { flexDirection: "row", flexWrap: "wrap", gap: 4, marginBottom: 8 },
  mediaImage: { width: "100%", height: 180, borderRadius: 10 },

  holeTag: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: 20,
    paddingHorizontal: 8,
    paddingVertical: 3,
    alignSelf: "flex-start",
    marginBottom: 6,
  },
  holeTagText: { color: Colors.textSecondary, fontSize: 11 },

  actionBar: { flexDirection: "row", gap: 20, paddingTop: 8, borderTopWidth: 1, borderTopColor: Colors.border },
  actionBtn: { flexDirection: "row", alignItems: "center", gap: 5 },
  actionText: { color: Colors.textSecondary, fontSize: 13 },

  // Comments
  commentsSection: { marginTop: 12, gap: 8 },
  noComments: { color: Colors.textSecondary, fontSize: 12, textAlign: "center" },
  commentRow: { flexDirection: "row", gap: 8, alignItems: "flex-start" },
  commentBubble: {
    flex: 1,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  commentAuthor: { color: Colors.text, fontWeight: "600", fontSize: 12 },
  commentBody: { color: "rgba(255,255,255,0.8)", fontSize: 12, marginTop: 2 },
  commentInput: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 4,
  },
  commentTextInput: {
    flex: 1,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: Colors.border,
    paddingHorizontal: 12,
    paddingVertical: 6,
    color: Colors.text,
    fontSize: 13,
  },
  commentSend: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(201,168,76,0.15)",
    alignItems: "center",
    justifyContent: "center",
  },

  // Avatar
  avatar: {
    backgroundColor: "rgba(201,168,76,0.2)",
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: { color: Colors.primary, fontWeight: "700" },

  // Empty state
  emptyState: { alignItems: "center", paddingVertical: 40, gap: 8 },
  emptyText: { color: Colors.text, fontWeight: "600", fontSize: 16 },
  emptySubText: { color: Colors.textSecondary, fontSize: 13 },

  // Load more
  loadMoreBtn: {
    alignItems: "center",
    paddingVertical: 16,
    marginTop: 8,
  },
  loadMoreText: { color: Colors.primary, fontWeight: "600" },

  // Modals
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  menuSheet: {
    backgroundColor: Colors.card,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingBottom: 30,
    paddingTop: 8,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 20,
    paddingVertical: 14,
  },
  menuItemText: { color: Colors.text, fontSize: 15 },

  reportSheet: {
    backgroundColor: Colors.card,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingBottom: 30,
    paddingTop: 20,
    paddingHorizontal: 20,
    borderWidth: 1,
    borderColor: Colors.border,
    gap: 4,
  },
  reportTitle: { color: Colors.text, fontWeight: "700", fontSize: 17, marginBottom: 12 },
  reportOption: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 10,
  },
  reportOptionSelected: {},
  reportOptionText: { color: Colors.text, fontSize: 15 },
  reportButtons: { flexDirection: "row", gap: 10, marginTop: 16, justifyContent: "flex-end" },
  reportCancelBtn: { paddingHorizontal: 16, paddingVertical: 10 },
  reportCancelText: { color: Colors.textSecondary, fontWeight: "600" },
  reportSubmitBtn: { backgroundColor: Colors.primary, borderRadius: 10, paddingHorizontal: 20, paddingVertical: 10 },
  reportSubmitText: { color: "#fff", fontWeight: "700" },
});
